package memoriaanimalessalvajes.views;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import memoriaanimalessalvajes.clases.DatosGenerales;
import memoriaanimalessalvajes.clases.DatosJuego;
import memoriaanimalessalvajes.views.Alertas.AlertaSalir;
import memoriaanimalessalvajes.views.paneles.PanelDiez;
import memoriaanimalessalvajes.views.paneles.PanelDoce;
import memoriaanimalessalvajes.views.paneles.PanelOcho;
import memoriaanimalessalvajes.views.paneles.PanelPrincipal;
import memoriaanimalessalvajes.views.paneles.PanelSeis;

public class PanelJuego extends javax.swing.JFrame {

    DatosJuego pares = DatosGenerales.pares;
    Timer timer;

    /**
     * Creates new form NewJFrame
     */
    public PanelJuego() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.Iniciar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal2 = new javax.swing.JPanel();
        panelGamer = new javax.swing.JPanel();
        panelCentral = new javax.swing.JPanel();
        btnSalir = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1500, 800));

        panelPrincipal2.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal2.setPreferredSize(new java.awt.Dimension(1500, 880));
        panelPrincipal2.setLayout(new java.awt.BorderLayout());

        panelGamer.setBackground(new java.awt.Color(255, 255, 255));
        panelGamer.setName(""); // NOI18N
        panelGamer.setPreferredSize(new java.awt.Dimension(1500, 750));
        panelGamer.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelGamerLayout = new javax.swing.GroupLayout(panelGamer);
        panelGamer.setLayout(panelGamerLayout);
        panelGamerLayout.setHorizontalGroup(
            panelGamerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1592, Short.MAX_VALUE)
        );
        panelGamerLayout.setVerticalGroup(
            panelGamerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        panelPrincipal2.add(panelGamer, java.awt.BorderLayout.PAGE_START);

        panelCentral.setBackground(new java.awt.Color(255, 255, 255));
        panelCentral.setMinimumSize(new java.awt.Dimension(1400, 50));
        panelCentral.setPreferredSize(new java.awt.Dimension(1500, 50));
        panelCentral.setLayout(new java.awt.BorderLayout());

        btnSalir.setBackground(new java.awt.Color(0, 102, 0));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.gray, java.awt.Color.gray));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setMinimumSize(new java.awt.Dimension(184, 50));
        btnSalir.setName(""); // NOI18N
        btnSalir.setPreferredSize(new java.awt.Dimension(184, 50));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salir del Juego");
        btnSalir.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 30));

        panelCentral.add(btnSalir, java.awt.BorderLayout.LINE_START);

        panelPrincipal2.add(panelCentral, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1592, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panelPrincipal2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked

        if (pares.getNumeroPares() == 5)
        {

            new AlertaSalir().setVisible(true);

        } else
        {
            int i = JOptionPane.showConfirmDialog(
                    null,
                    "Desea finalizar la partida actual? \n"
                    + " Advertencia: Si sales sus datos de esta partida se perderan. ",
                    "Abandonar Partida",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (i == 0)
            {
                pares.setNumeroPares(5);
                PanelPrincipal menu = new PanelPrincipal();
                panelprincipal(menu);

            }
        }

    }//GEN-LAST:event_btnSalirMouseClicked
    public void Iniciar() {
        PanelPrincipal menu = new PanelPrincipal();
        panelprincipal(menu);
        timer = new Timer(100, (ActionEvent e) ->
        {
            

            if (pares.isCambio())
            {
                pares.setCambio(false);
                
                switch (pares.getNumeroPares())
                {
                    
                    case 6:
                        PanelSeis seis = new PanelSeis();
                        panelprincipal(seis);
                        break;
                    case 8:
                        PanelOcho ocho = new PanelOcho();
                        panelprincipal(ocho);
                        break;
                    case 10:
                        PanelDiez diez = new PanelDiez();
                        panelprincipal(diez);
                        break;
                    case 12:
                        PanelDoce doce = new PanelDoce();
                        panelprincipal(doce);
                        break;
                    default:
                      
                        PanelPrincipal cinco = new PanelPrincipal();
                        panelprincipal(cinco);
                        break;
                }
            }
      
        });
        timer.start();
      
    }

    private JPanel panelprincipal(JPanel panelNuevo) {
        panelNuevo.setSize(1500, 750);
        panelNuevo.setLocation(0, 0);
        panelGamer.removeAll();
        panelGamer.add(panelNuevo);
        panelGamer.revalidate();
        panelGamer.repaint();
        return panelGamer;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() ->
        {
            new PanelJuego().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelGamer;
    private javax.swing.JPanel panelPrincipal2;
    // End of variables declaration//GEN-END:variables
}
